apiVersion: v1
description: Open Service Catalog Manager Asynchronous Provisioning Platform
name: oscm-app
version: 0.0.2
keywords:
  - oscm
  - app
sources:
  - https://github.com/servicecatalog/development
  - https://github.com/servicecatalog/oscm-dockerbuild
  - https://github.com/servicecatalog/oscm-helm
maintainers:
  - name: shimizuf
engine: gotpl
appVersion: 17.3.0
deprecated: false
